language: ruby
cache: bundler
rbenv:
- 2.4.1
services:
- postgresql
before_install:
- gem update --system
- gem install bundler:2.0.1
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: SKMQorJ7Rp0XINlVgXzgLyMHuXw1loSxIs311iIOhsrBK6KDlAL16AKR2ZOgTBMk4a6VejncdGrS9pMIjkOafQ1tULyR1z8TWtAVSTejQ6K81BWvxczoPo8FwdeQKufUd9O/QPhq6DiZLjLC9MRg2rW2IEc6D6jKRb5nWSNYQyyOGDl/WV6gyfi6xTmv885jfad4Ddj2xbSSM6Z41Oi3YOly4P1q8V+d7uvxOKyihU2c2UNOaNFMzgkyc3FCS5Vhl1e1wFcAVoxw7n+R0N5nE/5AjBAIdrHW2HvB9rom8T44eMZUPPpJ7+bnpdcYokEpZtlquf6qos2RC5zGZFyVuJQFE6gyw84a5N1uvhAQCbjbtKncMQ85bplXJ6M21a6WgGGNhquzavxd1p5de/JLDflcZmqbSFGtnegwV+Fgy9mgg0gubbUx04rdd/NLAXtRe8AXcWSin9MxQo03hGhZxzUuEM7AmCsWEsa5JbqrE5EqPPJlf9obB1lS7Uw5GXqdKT32nzNSO3LjifJ3qa+zOjCqd+QwhoUnuzW+B5G3T1xrYhoy4GixkNkNj0m2811UDAcYbEET2YW03Yly1OhO3tmuNCEVt7YNDncrk9IJNxPHV/aZfFjXAwEOPeguRQ/sYkPn/iSoGSaYciFkVyo34EjXJ/uH5sQL8q/Jll1FqfQ=
